# Generated by Django 3.2.3 on 2021-05-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0002_auto_20210518_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrerence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=244)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.image')),
            ],
        ),
    ]
